schema_version = "1.0.0"


id = "Industrial_Light_AOV_Splitter"
version = "1.0.0"
name = "Industrial Light AOV Splitter"
tagline = "Auto create better light aovs (diffuse_env, specular_env...)"
maintainer = "Roland Vyens"


type = "add-on"


website = "https://github.com/RolandVyens/Industrial-Light-AOV-Splitter"


tags = ["Compositing", "Import-Export", "Pipeline", "Render"]


blender_version_min = "4.2.0"


license = [
  "SPDX:GPL-3.0-or-later",
]